server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://luhpaglia-aws-mysql.cqqh5vlvc4li.us-east-2.rds.amazonaws.com:3306/Catalog
    username: admin
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher